// ========== FOTOS DE CHILE ==========
var nortePhotos = [
    { name:'Piedras Rojas', url:'https://drive.google.com/thumbnail?id=1F0IYAE6mROqz0nBtOrRL0-r-7xMQFwhb&sz=w400', zone:'norte', nota:'Formaciones rocosas en el altiplano, a más de 4.000m.' },
    { name:'Laguna Miscanti', url:'https://drive.google.com/thumbnail?id=1UQtlAR9wOdNBsC-E2XnYpLEbCXPDGtsA&sz=w400', zone:'norte', nota:'Laguna altiplánica en Antofagasta.' },
    { name:'Valle de la Luna', url:'https://drive.google.com/thumbnail?id=14Od2N2_ZkM4avnh1UiOHI6U3gqeMxLny&sz=w400', zone:'norte', nota:'Paisaje lunar en el Desierto de Atacama.' },
    { name:'Iglesia', url:'https://drive.google.com/thumbnail?id=1CU-oHqUlBsoeit8D7THQCnvdzeE3Ri0o&sz=w400', zone:'norte', nota:'San Pedro de Atacama.' },
    { name:'Flamenco', url:'https://drive.google.com/thumbnail?id=14Qdu0r0OuSeZgFb9-Nz1VSq0ytx_SqG1&sz=w400', zone:'norte', nota:'Fauna en el Salar de Atacama.' },
    { name:'La Portada', url:'https://drive.google.com/thumbnail?id=1cLUas6xEls2ZgtyI14qiX04KLDjroqcG&sz=w400', zone:'norte', nota:'Región de Antofagasta.' },
    { name:'Lagunas Escondidas de Baltinache', url:'https://drive.google.com/thumbnail?id=1dKEA6oYUsiEXfE5Yf2-Yp8Eu0f6baMvK&sz=w400', zone:'norte', nota:'Salar de Atacama.' },
    { name:'Desierto Florido', url:'https://drive.google.com/thumbnail?id=1zw6EbP5jjmpuM6izdhL9GTbrUPv2_pEg&sz=w400', zone:'norte', nota:'La magia del desierto chileno.' },
    { name:'Géiser del Tatio', url:'https://drive.google.com/thumbnail?id=1myfk3mUjy78mLbMvSe1pjdXw8uvRism-&sz=w400', zone:'norte', nota:'Aguas termales a más de 4.300m.' },
    { name:'Valle del Arcoíris', url:'https://drive.google.com/thumbnail?id=1glWxef_1S66sAAIwemQx1_KXEnPKwtam&sz=w400', zone:'norte', nota:'Cerros multicolores en el Desierto de Atacama.' },
    { name:'Lagunas Altiplánicas', url:'https://drive.google.com/thumbnail?id=19R2ZGOtvO9iOcLhOtVcTpDATOb4igup6&sz=w400', zone:'norte', nota:'Lagunas de altura en la Región de Antofagasta.' },
    { name:'Salar de Atacama', url:'https://drive.google.com/thumbnail?id=1grEzPHz96h3nI3Am8DRBbdN3PFs71-or&sz=w400', zone:'norte', nota:'El mayor salar de Chile.' },
];
var centroPhotos = [
    { name:'Costanera Center', url:'https://drive.google.com/thumbnail?id=1nGUkO0nawN3gOwjW21hXCIDNYPFegMt0&sz=w400', zone:'centro', nota:'Vista panorámica del centro.' },
    { name:'Castillo Wulff', url:'https://drive.google.com/thumbnail?id=1yv2VBxXp9gu27IFAm5tN-IiumJ7sspBe&sz=w400', zone:'centro', nota:'Viña del Mar.' },
    { name:'Cerro San Cristobal', url:'https://drive.google.com/thumbnail?id=1HCxBgrT5lDyhSLe2otrp4w2ugBBDXSbX&sz=w400', zone:'centro', nota:'Santiago.' },
    { name:'Cerro Santa Lucía', url:'https://drive.google.com/thumbnail?id=1R-r4Tt1TIc9A7VJ1_-_iXy2P2NpZfOsN&sz=w400', zone:'centro', nota:'Santiago.' },
    { name:'Cordillera de Los Andes', url:'https://drive.google.com/thumbnail?id=1Vy-KF3PCdLQTPg-9grzLVjyWTebzlCHb&sz=w400', zone:'centro', nota:'Hermosa vista desde la capital.' },
    { name:'Atardecer desde Santiago', url:'https://drive.google.com/thumbnail?id=1PyuMXVS-J7z4Ch1u3mFt27E6wmkpEK5L&sz=w400', zone:'centro', nota:'Con la cordillera de fondo.' },
    { name:'Embalse El Yeso', url:'https://drive.google.com/thumbnail?id=1Ay1YRncILC0rm0QZM_cEn2Vodu23cOCd&sz=w400', zone:'centro', nota:'Cajón del Maipo.' },
    { name:'Centro de Santiago', url:'https://drive.google.com/thumbnail?id=1VqAz0OrJZ3kufu5_yj7M6zs1NgUy6Byw&sz=w400', zone:'centro', nota:'Zona urbana de comercio.' },
    { name:'Barrio Lastarria', url:'https://drive.google.com/thumbnail?id=16yL_2czoYeGo8Ps0yq2eAunMaMnx2e0F&sz=w400', zone:'centro', nota:'Lugar de encuentro de artistas y comerciantes.' },
    { name:'Viñedos', url:'https://drive.google.com/thumbnail?id=1xFEIBTub8gBh1W5KRq2_ZBiUNmrFFJnH&sz=w400', zone:'centro', nota:'Valle Central.' },
    { name:'Parque Nacional La Campana', url:'https://drive.google.com/thumbnail?id=1j6zc5a3Fs66WF4RNzL8CS0DxNrgeH9ll&sz=w400', zone:'centro', nota:'Reserva de la biosfera en la Región de Valparaíso.' },
    { name:'Caleta Horcón', url:'https://drive.google.com/thumbnail?id=1891kWifKa-U9pkBRtkPRtmpR09IRPpsm&sz=w400', zone:'centro', nota:'Pueblo costero con tradición pesquera.' },
];
var surPhotos = [
    { name:'Palafitos', url:'https://drive.google.com/thumbnail?id=1AmW36m9FQyk4YCmIIl4jT_pML24l5p8d&sz=w400', zone:'sur', nota:'Castro Chiloé.' },
    { name:'Rio Calle Calle', url:'https://drive.google.com/thumbnail?id=120O2TkWrtd-pJnsCqv6ktR3Z-kXZ_37i&sz=w400', zone:'sur', nota:'Valdivia.' },
    { name:'Volcán Villarrica', url:'https://drive.google.com/thumbnail?id=1X-7YtR48yGYGfRasz4mLOgnx8RsXPCPC&sz=w400', zone:'sur', nota:'Hermosa vista desde La Poza de Pucón.' },
    { name:'Río Tolten', url:'https://drive.google.com/thumbnail?id=1yR4_putOUKXtkjcFUp4j680VCMiZpB6b&sz=w400', zone:'sur', nota:'Región de la Araucanía.' },
    { name:'Selva valdiviana', url:'https://drive.google.com/thumbnail?id=1CfegotOgyuSQ_3LpVQRYUeFOgcepX8jB&sz=w400', zone:'sur', nota:'Región de los Ríos.' },
    { name:'Volcán Osorno', url:'https://drive.google.com/thumbnail?id=1qHxn6xYIMKduZ55urTczocbY8pQo6fL0&sz=w400', zone:'sur', nota:'Saltos de Petrohue.' },
    { name:'Puerto Varas', url:'https://drive.google.com/thumbnail?id=1c8lbpmfV_tPnO7RFu_BJ4wWJMgIgAeue&sz=w400', zone:'sur', nota:'Lago Llanquihue.' },
    { name:'Mercado fluvial', url:'https://drive.google.com/thumbnail?id=1t0G1sHMmV0EfZFa3J2wlpW6qzb2Zexai&sz=w400', zone:'sur', nota:'Valdivia.' },
    { name:'Martin pescador', url:'https://drive.google.com/thumbnail?id=1MDDIDV3T6IOPgE5tXsF0TgP_ZBun-xhK&sz=w400', zone:'sur', nota:'Fauna del sur.' },
    { name:'Volcán Lonquimay y araucarias', url:'https://drive.google.com/thumbnail?id=1Y1KoBuViE5kXhMI8jXs0NptFhYQcRlgS&sz=w400', zone:'sur', nota:'Reserva Nacional Malalcahuello.' },
    { name:'Puente Rodrigo de Bastidas', url:'https://drive.google.com/thumbnail?id=1uovAMwK7ud7r3byH3y31ESh2-_z6Uuup&sz=w400', zone:'sur', nota:'Rio Tolten Villarrica.' },
    { name:'Viaducto del Malleco', url:'https://drive.google.com/thumbnail?id=15HOHLT2otsmj5AJ5pDmv5k8h3VtlzjSC&sz=w400', zone:'sur', nota:'Región de la Araucanía.' },
];
var patagoniaPhotos = [
    { name:'Torres del Paine', url:'https://drive.google.com/thumbnail?id=15ax4Kz362p7z5yTjbgd8z9b98ha3HfTh&sz=w400', zone:'austral', nota:'Puerto Natales.' },
    { name:'Punta Arenas', url:'https://drive.google.com/thumbnail?id=18bTBxQKTjcVHaBdkZpPh967esE5MD1PL&sz=w400', zone:'austral', nota:'Región de Magallanes.' },
    { name:'Lago Grey', url:'https://drive.google.com/thumbnail?id=1-o2SJrZDqQE64vESRbYExBcEH1lzHaPW&sz=w400', zone:'austral', nota:'Torres del Paine.' },
    { name:'Glaciar Grey', url:'https://drive.google.com/thumbnail?id=1_VLPDVx6WBuBiA4hEegwtLWGZJ285DMB&sz=w400', zone:'austral', nota:'Hielo azul eterno.' },
    { name:'Valle del Francés', url:'https://drive.google.com/thumbnail?id=1tVxHCA0R_4f4apJse_hvco32R0nVHc3R&sz=w400', zone:'austral', nota:'Paisajes increíbles.' },
    { name:'Estancia Patagónica', url:'https://drive.google.com/thumbnail?id=1cY0MZt2mekm40M0lynkh6CypXNX4PZ-G&sz=w400', zone:'austral', nota:'La soledad más bella del planeta.' },
    { name:'Lago Pehoé', url:'https://drive.google.com/thumbnail?id=1NpBgGLaGErifAqGG0m5cjJR2zfmB07x7&sz=w400', zone:'austral', nota:'Estepa y montaña en perfecta unión.' },
    { name:'Canal Beagle', url:'https://drive.google.com/thumbnail?id=1Y--szySJeRA54gtRZgMWX2rXLoURu654&sz=w400', zone:'austral', nota:'Ríos de hielo entre cumbres nevadas.' },
    { name:'Cabo de Hornos', url:'https://drive.google.com/thumbnail?id=1exOBlMQYYveF6J02irHIofpI2nUo9U7A&sz=w400', zone:'austral', nota:'La Patagonia profunda te espera.' },
    { name:'Isla Magdalena', url:'https://drive.google.com/thumbnail?id=1awWCm8OHQ2vUPdR1-1XVSyqBXKXDIopk&sz=w400', zone:'austral', nota:'Colores imposibles en el extremo sur.' },
    { name:'Puerto Williams', url:'https://drive.google.com/thumbnail?id=1YUC001Cd2vKwxNyV1ri1nlcDcQY3yxip&sz=w400', zone:'austral', nota:'Tierra de gigantes y leyendas.' },
    { name:'Ventisquero Colgante', url:'https://drive.google.com/thumbnail?id=1PQ9x8ocUO_H2l7QmCHguro8M0HJS4aPW&sz=w400', zone:'austral', nota:'Glaciar colgante en la Patagonia chilena.' },
];
var argentinaNortePhotos = [
    { name:'Quebrada de Humahuaca', url:'https://drive.google.com/thumbnail?id=1uwaDZGOxkdgwZh-Xb3kDYdjB7BVHEVyh&sz=w400', zone:'argentina-norte', nota:'Patrimonio de la Humanidad en Jujuy.' },
    { name:'Cerro de los Siete Colores', url:'https://drive.google.com/thumbnail?id=1xGdn2yjxwquDyAQKBsmg9INXr4NomCzk&sz=w400', zone:'argentina-norte', nota:'Ícono de Purmamarca, Jujuy.' },
    { name:'Salinas Grandes', url:'https://drive.google.com/thumbnail?id=1xGdn2yjxwquDyAQKBsmg9INXr4NomCzk&sz=w400', zone:'argentina-norte', nota:'Desierto de sal entre Jujuy y Salta.' },
    { name:'Cuesta de Lipán', url:'https://drive.google.com/thumbnail?id=16NaOVDOdGL_5bO5e9Rzco76T28hcId_W&sz=w400', zone:'argentina-norte', nota:'Carretera de montaña con vistas increíbles.' },
    { name:'Pucará de Tilcara', url:'https://drive.google.com/thumbnail?id=1iOlTgQKYeUv8CmL5eo_Xji-c0x19NTX8&sz=w400', zone:'argentina-norte', nota:'Fortaleza prehispánica en Jujuy.' },
    { name:'Cafayate', url:'https://drive.google.com/thumbnail?id=1JoGF-I8Tjy6xJ0YlO1THzJKMPqrNytBk&sz=w400', zone:'argentina-norte', nota:'Tierra de viñedos en Salta.' },
    { name:'Tren a las Nubes', url:'https://drive.google.com/thumbnail?id=168XM8s329lphZbPB8lWBu_EzdtUHJgV6&sz=w400', zone:'argentina-norte', nota:'Recorrido ferroviario a más de 4.000m.' },
    { name:'Ruinas de Quilmes', url:'https://drive.google.com/thumbnail?id=1b217TXK5tARb4E5ha8gpOJsqd1J-MAjK&sz=w400', zone:'argentina-norte', nota:'Restos de la civilización diaguita.' },
    { name:'Campo de Piedra Pómez', url:'https://drive.google.com/thumbnail?id=1hkSjwTHKIeiTc7SSUQX-3mMJ0IYHry4r&sz=w400', zone:'argentina-norte', nota:'Paisaje lunar en Catamarca.' },
    { name:'Volcán Llullaillaco', url:'https://drive.google.com/thumbnail?id=160i15aGgwKQUp9zvFkF97QsdQYaXsJO_&sz=w400', zone:'argentina-norte', nota:'Uno de los volcanes más altos del mundo.' },
    { name:'Museo de Arqueología de Alta Montaña', url:'https://drive.google.com/thumbnail?id=1SbJeLKXcy3GJIC3BIPqcWFMAtJFcqu1t&sz=w400', zone:'argentina-norte', nota:'Hogar de los Niños de Llullaillaco.' },
    { name:'Termas de Reyes', url:'https://drive.google.com/thumbnail?id=1V4iPmI3BV6VfCrl6a391vg7pGdXoiySI&sz=w400', zone:'argentina-norte', nota:'Aguas termales en Jujuy.' },
];
var argentinaCentroPhotos = [
    { name:'Obelisco', url:'https://drive.google.com/thumbnail?id=10ZOMdYNbi5kOhyMKx5eHkkjNZUm_jl6I&sz=w400', zone:'argentina-centro', nota:'El ícono de Buenos Aires, inaugurado en 1936.' },
    { name:'Barrio La Boca', url:'https://drive.google.com/thumbnail?id=1zrmqqgnLiZyi5ZWeCNtL_MkdPX_h6PsI&sz=w400', zone:'argentina-centro', nota:'Casas de colores y tango en Buenos Aires.' },
    { name:'Mar del Plata', url:'https://drive.google.com/thumbnail?id=10sHvR-SShb3lgvR7Bdn6cUt_xWdEijPz&sz=w400', zone:'argentina-centro', nota:'Playas y puerto de la costa atlántica.' },
    { name:'Sierras de Córdoba', url:'https://drive.google.com/thumbnail?id=1kR5_cjsNN0pQC-J3BrhBKIBI-Bq9s8bU&sz=w400', zone:'argentina-centro', nota:'Paisaje serrano en el centro argentino.' },
    { name:'Bodega Mendoza', url:'https://drive.google.com/thumbnail?id=1WvP8y01OhQ_mpCxaIzwUuXyNE4GT7Kun&sz=w400', zone:'argentina-centro', nota:'Ruta del vino en la región de Cuyo.' },
    { name:'Cerro de la Gloria', url:'https://drive.google.com/thumbnail?id=1HC3JynlYZZ1SuR-51nO7jJhCisDxx97x&sz=w400', zone:'argentina-centro', nota:'Monumento histórico en Mendoza.' },
    { name:'Teatro Colón', url:'https://drive.google.com/thumbnail?id=1Rw51ZPGayYMNoGgXVkSkvl9yYkwpVaGe&sz=w400', zone:'argentina-centro', nota:'Uno de los teatros de ópera más importantes del mundo.' },
    { name:'Puente Colgante', url:'https://drive.google.com/thumbnail?id=1IrFr17SSrT_yh4exd19gse-IKkSKM2du&sz=w400', zone:'argentina-centro', nota:'Ícono de la ciudad de Santa Fe.' },
    { name:'Reloj Cucú', url:'https://drive.google.com/thumbnail?id=1NA9uzV_uaF9ri3HbF_ZAVdWnuk_VpXgp&sz=w400', zone:'argentina-centro', nota:'Atracción turística de La Falda, Córdoba.' },
    { name:'Bosques de Palermo', url:'https://drive.google.com/thumbnail?id=1uIr44S0CaPur3-w64phRPawwL9leVn0Z&sz=w400', zone:'argentina-centro', nota:'Pulmón verde de la Ciudad de Buenos Aires.' },
    { name:'Catedral de Salta', url:'https://drive.google.com/thumbnail?id=1lkzlryApUwl3UiTqIUJLqNVOCX3h-_BI&sz=w400', zone:'argentina-centro', nota:'Arquitectura colonial en el norte argentino.' },
    { name:'Cabildo de Buenos Aires', url:'https://drive.google.com/thumbnail?id=1Hhm3aqA4654w9zRqGGEOkcpNhBNZk6qj&sz=w400', zone:'argentina-centro', nota:'Histórico edificio de la época colonial.' },
];
var argentinaPatagoniaPhotos = [
    { name:'Glaciar Perito Moreno', url:'https://drive.google.com/thumbnail?id=1CpP4mNkUsguTJc3ogku5O_rFvznW3oOl&sz=w400', zone:'argentina-patagonia', nota:'El glaciar más famoso de la Patagonia argentina.' },
    { name:'Ushuaia', url:'https://drive.google.com/thumbnail?id=1mhDWXZwJMPdRmuMSMmmFjagu0HrYrheu&sz=w400', zone:'argentina-patagonia', nota:'La ciudad más austral del mundo.' },
    { name:'Cerro Chaltén', url:'https://drive.google.com/thumbnail?id=1qfmMulhoOaDGYTBDAyX7tc9NOLgiactp&sz=w400', zone:'argentina-patagonia', nota:'Imponente montaña en la Patagonia.' },
    { name:'Bariloche', url:'https://drive.google.com/thumbnail?id=1Tny2syXcCZbm-GzlTT10I6MsQ_QjA6uW&sz=w400', zone:'argentina-patagonia', nota:'Lagos y montañas en Río Negro.' },
    { name:'Cueva de las Manos', url:'https://drive.google.com/thumbnail?id=1thIyH39oAdz1xMuMVaGz_kzLgbN8T4fQ&sz=w400', zone:'argentina-patagonia', nota:'Pinturas rupestres de más de 9.000 años.' },
    { name:'Puerto Madryn', url:'https://drive.google.com/thumbnail?id=1DJ4I59mDo4ezdBpmtwtihRao9aB62_cy&sz=w400', zone:'argentina-patagonia', nota:'Avistaje de ballenas en Chubut.' },
    { name:'Tren del Fin del Mundo', url:'https://drive.google.com/thumbnail?id=13fSVdYz8QQCMlpfuL0zI6hKBFL_akKPN&sz=w400', zone:'argentina-patagonia', nota:'Ferrocarril histórico en Ushuaia.' },
    { name:'Lago Argentino', url:'https://drive.google.com/thumbnail?id=1vOIHBROl5MttXEkydQjd-zPTAVavugpO&sz=w400', zone:'argentina-patagonia', nota:'El lago más grande de Argentina.' },
    { name:'Bosque Petrificado', url:'https://drive.google.com/thumbnail?id=1KvTg6KlQu_yasKc93hVY5vc0jQt-r-DC&sz=w400', zone:'argentina-patagonia', nota:'Restos fósiles en Santa Cruz.' },
    { name:'El Calafate', url:'https://drive.google.com/thumbnail?id=1qMcxmtSV4WUmtBtg7m9u8CpsuOg1a9DQ&sz=w400', zone:'argentina-patagonia', nota:'Puerta de entrada al glaciar Perito Moreno.' },
    { name:'Cerro Tronador', url:'https://drive.google.com/thumbnail?id=1R2sw4o75kemK39snxurKc-AtX_8VA7r-&sz=w400', zone:'argentina-patagonia', nota:'Montaña con glaciares colgantes.' },
    { name:'Punta Tombo', url:'https://drive.google.com/thumbnail?id=1EVi3-6eyImqmdGu_11bBBEg42XC4Fs61&sz=w400', zone:'argentina-patagonia', nota:'La colonia de pingüinos más grande de Sudamérica.' },
];
var argentinaLitoralPhotos = [
    { name:'Cataratas del Iguazú', url:'https://drive.google.com/thumbnail?id=1OuzQI_YpKYOVwc9KwRwNmXN6OdCjRtTW&sz=w400', zone:'argentina-litoral', nota:'Maravilla natural en Misiones, frontera con Brasil.' },
    { name:'Parque Nacional Talampaya', url:'https://drive.google.com/thumbnail?id=1uxxaHlPhEaU4bAl4uVUL9rmHlm79ZMmh&sz=w400', zone:'argentina-litoral', nota:'Formaciones rocosas en La Rioja.' },
    { name:'Ruinas de San Ignacio', url:'https://drive.google.com/thumbnail?id=1jRCowaPfltVWht7n-v_6PdEhua3YpFXt&sz=w400', zone:'argentina-litoral', nota:'Misiones jesuíticas en Misiones.' },
    { name:'Puerto Iguazú', url:'https://drive.google.com/thumbnail?id=1Frz-zvaqu72Jzw3s6Y687JtVCrVclEz2&sz=w400', zone:'argentina-litoral', nota:'Ciudad fronteriza con Brasil y Paraguay.' },
    { name:'Costanera de Rosario', url:'https://drive.google.com/thumbnail?id=1OeE1B0kFzgggFyWevpQyIF_IdHGV_dSV&sz=w400', zone:'argentina-litoral', nota:'Paseo junto al río Paraná.' },
    { name:'Parque Nacional El Palmar', url:'https://drive.google.com/thumbnail?id=1s_E0F1wrwNBEHaIcjt7L0dO1P6tcXraM&sz=w400', zone:'argentina-litoral', nota:'Palmeras yatay en Entre Ríos.' },
    { name:'Termas de Colón', url:'https://drive.google.com/thumbnail?id=1WWCbcu93lI3lUlXRJQdsoWIEL9oUP74i&sz=w400', zone:'argentina-litoral', nota:'Aguas termales en Entre Ríos.' },
    { name:'Esteros del Iberá', url:'https://drive.google.com/thumbnail?id=1yLmtbooXH-0mtJdC4lHPsd90bqrj3d10&sz=w400', zone:'argentina-litoral', nota:'Humedales y fauna en Corrientes.' },
    { name:'Basílica de Luján', url:'https://drive.google.com/thumbnail?id=11jON7WP6SKzhhwrBT5kyc_B36EA1oSXA&sz=w400', zone:'argentina-litoral', nota:'Santuario católico en Buenos Aires.' },
    { name:'Monumento a la Bandera', url:'https://drive.google.com/thumbnail?id=1e8iXmJwVlPv-PogjsexcSjODR5wnZKq5&sz=w400', zone:'argentina-litoral', nota:'Ícono de la ciudad de Rosario.' },
    { name:'Puente Rosario-Victoria', url:'https://drive.google.com/thumbnail?id=1HDySZD2cL6j_zUKtAwrDZ3Ooy_FivXiv&sz=w400', zone:'argentina-litoral', nota:'Conecta Rosario con Victoria.' },
    { name:'Mina Wanda', url:'https://drive.google.com/thumbnail?id=1ZZNrOEqdcVIT_sbdr57FkeeEnOZJcls6&sz=w400', zone:'argentina-litoral', nota:'Mina de piedras preciosas en Misiones.' },
];
var mexicoNortePhotos = [
    { name:'Cañón del Cobre', url:'https://drive.google.com/thumbnail?id=11iYN2ZNRxF6jSGqL2kq5euBNLniu_Qqw&sz=w400', zone:'mexico-norte', nota:'Sistema de cañones en Chihuahua, más grande que el del Colorado.' },
    { name:'Dunas de Samalayuca', url:'https://drive.google.com/thumbnail?id=1dAzA4IjDqVzn4X5VdGXgmfywYmHS5ntk&sz=w400', zone:'mexico-norte', nota:'Imponentes dunas en el desierto de Chihuahua.' },
    { name:'Cascada de Basaseachi', url:'https://drive.google.com/thumbnail?id=1EgLFXZgc_J8vbapy49cnMxEzhxyph3lF&sz=w400', zone:'mexico-norte', nota:'La cascada más alta de México con 246 metros.' },
    { name:'Sierra del Carmen', url:'https://drive.google.com/thumbnail?id=1z0lvQo__xxUZIiUDJVTOV7Pqoto3EFJd&sz=w400', zone:'mexico-norte', nota:'Reserva natural en la frontera de Coahuila y Texas.' },
    { name:'Cumbres de Monterrey', url:'https://drive.google.com/thumbnail?id=17v9d89qxcwarJt1KnjlSN4MQ-Oa3xbx-&sz=w400', zone:'mexico-norte', nota:'Imponentes montañas en Nuevo León.' },
    { name:'Grutas de García', url:'https://drive.google.com/thumbnail?id=1GNOu7WhWT21V2Nmbb5NGODSdVQ3OBah9&sz=w400', zone:'mexico-norte', nota:'Impresionantes cuevas en Nuevo León.' },
    { name:'Valle de los Fantasmas', url:'https://drive.google.com/thumbnail?id=1IIPmf-hcvKGmKeB8Uq6p6n38DSR5EI_Z&sz=w400', zone:'mexico-norte', nota:'Formaciones rocosas únicas en Nuevo León.' },
    { name:'Zona del Silencio', url:'https://drive.google.com/thumbnail?id=1CNLEvaIPuMohelHfZPR2bZ0JaJuxvv6Z&sz=w400', zone:'mexico-norte', nota:'Área desértica en Durango rodeada de misterio.' },
    { name:'Puente Baluarte', url:'https://drive.google.com/thumbnail?id=17743PcwVJF8hXz-Kjqcwx1DWDR-C0PnA&sz=w400', zone:'mexico-norte', nota:'El puente atirantado más alto de América.' },
    { name:'Isla Tiburón', url:'https://drive.google.com/thumbnail?id=16YR-PBB-Mlovp-T6UCpsGrUM3aeHOSRw&sz=w400', zone:'mexico-norte', nota:'La isla más grande de México, en Sonora.' },
    { name:'Desierto de Altar', url:'https://drive.google.com/thumbnail?id=1aNchwj76SLEtXEteKqItWqtLFI70pTLX&sz=w400', zone:'mexico-norte', nota:'Vasto desierto en Sonora con dunas cambiantes.' },
    { name:'Creel', url:'https://drive.google.com/thumbnail?id=1hfZpv99DoeOXjtvyOVrfs6BZrZMQcVoL&sz=w400', zone:'mexico-norte', nota:'Pueblo Mágico en la Sierra Tarahumara.' },
];
var mexicoCentroPhotos = [
    { name:'Zócalo CDMX', url:'https://drive.google.com/thumbnail?id=1C8XZ_N5u8Ajtpl6i9kQ0zr3zycifaGN7&sz=w400', zone:'mexico-centro', nota:'Plaza principal de la Ciudad de México.' },
    { name:'Bellas Artes', url:'https://drive.google.com/thumbnail?id=1WI5QZB_qHtzD_RX5NgHZza4VWfJWqrH0&sz=w400', zone:'mexico-centro', nota:'Ícono cultural de la Ciudad de México.' },
    { name:'Xochimilco', url:'https://drive.google.com/thumbnail?id=1VsZs5alPe9h7xHeYfiHGbsx6Mr54KVBT&sz=w400', zone:'mexico-centro', nota:'Canales y trajineras en la Ciudad de México.' },
    { name:'Basílica de Guadalupe', url:'https://drive.google.com/thumbnail?id=1mPie5m_w8rcyqeiHN393qhC2vHQhHP8C&sz=w400', zone:'mexico-centro', nota:'Santuario mariano más visitado del mundo.' },
    { name:'Teotihuacán', url:'https://drive
